#!/bin/bash
#
# ⠀⠀⠀⠀⠀⠀⠀⠀⢀⡀⠀⣠⣄⠀⠀⠀⠀⠀⠀
#⠀⠀⠀⠀⠀⠀⡠⠖⣿⣧⢻⣿⢿⣷⣤⡀⠄⠀⠀⠀display-rotate
#⠀⠀⠀⠀⣠⠊⠀⠂⣿⡏⣾⣿⠈⢻⠟⠉⠀⠀⠀⠀--------------
#⠀⠀⠀⢸⣿⠀⠀⢰⣿⣷⢻⣿⠴⣿⣷⣦⡀⠀⠀⠀Switch the main display between vertical and horizontal.
#⠀⠀⠀⣿⣿⡄⠀⡇⣿⣧⣿⣿⠀⠈⢿⣿⡇⠀⠀⠀
#⠀⠀⠀⠈⢿⣿⣦⣱⠃⠀⣿⠟⠁⠀⠀⡿⠃⠀⠀⠀Only meant to be used on Foxes, since she has the fancy
#⠀⠀⠀⠀⠀⠙⢿⣿⣿⣶⣧⣤⣤⡤⠚⠁⠀⠀⠀⠀rotating main display.
#⠀⠀⠀⠀⠀⠀⠀⠌⠉⠛⠛⠛⠉⠀⠀⠀⠀⠀⠀⠀
#
# -----------------------------------------------------------------------------

headline="Rotating display"
icon="computer"
messagev="Switching to vertical display."
messageh="Switching to horizontal display."
messageerror="Display rotation is meant to be used on Foxes."

case $HOSTNAME in
	foxes)
		xrandr -q | grep "HDMI-2" | grep "1920x1200"
		if [ $? -eq 0 ]; then
			echo "Switching display to vertical."
			notify-send -i "$icon" "$headline" "$messagev"
			sleep 1s
			xrandr --output HDMI-2 --rotate left
		else
			echo "Switching display to horizontal."
			notify-send -i "$icon" "$headline" "$messageh"
			sleep 1s
			xrandr --output HDMI-2 --rotate normal
		fi
		;;
	*)
		notify-send -i "$icon" "$headline" "$messageerror"
		;;
esac
