#!/bin/bash
# ⠀⠀⠀⠀⠀⠀⠀⠀⢀⡀⠀⣠⣄⠀⠀⠀⠀⠀⠀
#⠀⠀⠀⠀⠀⠀⡠⠖⣿⣧⢻⣿⢿⣷⣤⡀⠄⠀⠀⠀
#⠀⠀⠀⠀⣠⠊⠀⠂⣿⡏⣾⣿⠈⢻⠟⠉⠀⠀⠀⠀rofi-run
#⠀⠀⠀⢸⣿⠀⠀⢰⣿⣷⢻⣿⠴⣿⣷⣦⡀⠀⠀⠀--------
#⠀⠀⠀⣿⣿⡄⠀⡇⣿⣧⣿⣿⠀⠈⢿⣿⡇⠀⠀⠀All-in-one (mostly) rofi script, based on the script
#⠀⠀⠀⠈⢿⣿⣦⣱⠃⠀⣿⠟⠁⠀⠀⡿⠃⠀⠀⠀included in ArchLabs
#⠀⠀⠀⠀⠀⠙⢿⣿⣿⣶⣧⣤⣤⡤⠚⠁⠀⠀⠀
#⠀⠀⠀⠀⠀⠀⠀⠌⠉⠛⠛⠛⠉⠀⠀⠀⠀⠀⠀⠀

NAME="${0##*/}"
VER="1.0"
OPTS=(
	-padding 50
	-line-padding 4
	-hide-scrollbar
)

usage()
{
	cat <<EOF

 Rofi launch script based off of rofi_run, included in ArchLabs.

 USAGE:  $NAME [OPTIONS]

 OPTIONS:

     -h,--help          Display this message

     -v,--version       Display script version

     -r,--run           Run launcher

     -d,--drun          Desktop application launcher

     -w,--window        Switch between windows

     -l,--logout        System logout dialog

     -b,--browser       Browser search by keyword (requires surfraw)

     -c,--calculator    Persistant calculator dialog (requires libqalculate)


  Without any options the run dialog will be opened.

EOF
}

if (( $# == 0 )); then
	rofi -show drun "${OPTS[@]}"
else
	for arg in "$@"; do
		case $arg in
			-h|--help)
				usage
				exit 0
				;;
			-v|--version)
				echo -e "$NAME -- Version $VER"
				exit 0
				;;
			-d|--drun)
				rofi -i -show drun "${OPTS[@]}"
				;;
			-r|--run)
				rofi -i -show run "${OPTS[@]}"
				;;
			-w|--window)
				rofi -i -show window "${OPTS[@]}"
				;;
			-e|--emoji)
				[ -d "/usr/share/rofi-emoji/" ] || { echo "Requires 'rofi-emoji' installed"; exit 1; }
				rofi -i -show emoji "${OPTS[@]}"
				;;
			-c|--calculator)
				hash qalc >/dev/null 2>&1 || { echo "Requires 'libqalculate' installed"; exit 1; }
				rofi -i -show calc "${OPTS[@]}"
				;;
			# -c|--clipboard)
			# 	hash greenclip >/dev/null 2>&1 || { echo "Requires 'greenclip' installed"; exit 1; }
			# 	rofi -modi "clipboard:greenclip print" -show "clipboard:greenclip print" "${OPTS[@]}"
			# 	;;
			# -b|--browser)
			# 	hash surfraw >/dev/null 2>&1 || { echo "Requires 'surfraw' installed"; exit 1; }
			# 	surfraw -browser="$BROWSER" "$(sr -elvi | awk -F'-' '{print $1}' | sed '/:/d' | awk '{$1=$1};1' |
			# 		rofi -hide-scrollbar -kb-row-select 'Tab' -kb-row-tab 'Control+space' \
			# 			-dmenu -mesg 'Tab for Autocomplete' -i -p 'Web Search')"
			# 	;;
			-l|--logout)
				case "$(rofi -sep "|" -dmenu -i -l 5 -p 'Power options:' <<< " Lock| Log out|鈴 Suspend|⥁ Reboot| Shutdown")" in
					*Lock) betterlockscreen -l dim --off 60;;
					*Shutdown) systemctl poweroff ;;
					*Reboot) systemctl reboot ;;
					*Suspend) systemctl suspend ;;
					*Log\ out) loginctl terminate-session $XDG_SESSION_ID ;;
				esac
				;;
			*)
				printf "\nOption does not exist: %s\n\n" "$arg"
				exit 2
		esac
	done
fi

exit 0
