#!/usr/bin/env bash
#------------------------------------------------------------------------------
# rofi-conf
# adolf@gatoneg.ro
# https://github.com/adolfgatonegro
#------------------------------------------------------------------------------
# Shell script to access frequently-used config files through rofi
#------------------------------------------------------------------------------ 

declare -a options=(
	"dunst - $XDG_CONFIG_HOME/dunst/dunstrc"
	"git - $XDG_CONFIG_HOME/git/config"
	"kitty - $XDG_CONFIG_HOME/kitty/kitty.conf"
	"neovim colorscheme - $XDG_CONFIG_HOME/nvim/lua/gatonegro/colorscheme.lua"
	"neovim comp - $XDG_CONFIG_HOME/nvim/lua/gatonegro/cmp.lua"
	"neovim init - $XDG_CONFIG_HOME/nvim/init.lua"
	"neovim keymaps - $XDG_CONFIG_HOME/nvim/lua/gatonegro/keymaps.lua"
	"neovim options - $XDG_CONFIG_HOME/nvim/lua/gatonegro/options.lua"
	"neovim plugins - $XDG_CONFIG_HOME/nvim/lua/gatonegro/plugins.lua"
	"picom - $XDG_CONFIG_HOME/picom/picom.conf"
	"qtile autostart - $XDG_CONFIG_HOME/qtile/scripts/autostart.sh"
	"qtile config - $XDG_CONFIG_HOME/qtile/config.py"
	"qtile groups - $XDG_CONFIG_HOME/qtile/groups.py"
	"qtile hooks - $XDG_CONFIG_HOME/qtile/hooks.py"
	"qtile keys - $XDG_CONFIG_HOME/qtile/keys.py"
	"qtile layouts - $XDG_CONFIG_HOME/qtile/layouts.py"
	"qtile screens - $XDG_CONFIG_HOME/qtile/screens.py"
	"rofi - $XDG_CONFIG_HOME/rofi/config.rasi"
	"sxhkd - $XDG_CONFIG_HOME/sxhkd/sxhkdrc"
	"vifm - $XDG_CONFIG_HOME/vifm/vifmrc"
	"x11 xinitrc - $XDG_CONFIG_HOME/X11/xinitrc"
	"x11 xprofile - $XDG_CONFIG_HOME/X11/xprofile"
	"zsh aliases - $ZDOTDIR/zsh-aliases"
	"zsh config - $ZDOTDIR/.zshrc"
	"zsh environment - $HOME/.zshenv"
	"zsh functions - $ZDOTDIR/zsh-functions"
	"zsh history - $ZDOTDIR/zsh-hist"
	"zsh profile - $ZDOTDIR/.zprofile"
)

choice=$(printf '%s\n' "${options[@]}" | rofi -i -dmenu -l 10 -p 'Edit config:')

if [ "$choice" ]; then
	cfg=$(printf '%s\n' "${choice}" | awk '{print $NF}')
	kitty -e nvim "$cfg"

else
	exit 1
fi
